language: python
python:
    - "2.6"
    - "2.7"
# command to install dependencies
install:
    - "pip install -r requirements.txt --use-mirrors"
    #Temporal solution to travis issue #155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
# command to run tests
script:
    - pycopipe.py --mode test --test_name_re "test_.*"
